### ISSUE TITLE
command completion?

### ISSUE THREAD

**Issue by thowe** [japhb/Terminal-LineEditor#1]
Hello!  I'm just curious if this could be used to do command completion?
It's not obvious to me how I would do that from the README, but perhaps there is a way I don't see.
Trailing question mark or TAB that shows possible command options and also disambiguated  short forms
of commands are things I had in mind.

**Comment by japhb** [comment]
Hi there!  Yes, there is (primitive) tab completion functionality.  It hadn't been added to the README mostly because I hadn't decided if more needed to be done to support more advanced tab completion, so I didn't want to ensconce a likely-to-change API.

However, if you're fine with trying it out and possibly having to update your code in the future, you can look to the [LineEditor code used in the Rakudo REPL](https://github.com/rakudo/rakudo/blob/master/src/core.c/REPL.pm6#L103).  It's mostly a matter of instantiating the `CLIInput` object with a callback that will choose the current completions (this is where your magic expansion algorithm goes), and updating the completion context if needed before reading each input line.

You'll end up with a tab completion system similar to the one supported by Linenoise -- which is pretty darn minimal, but it does work.

**Comment by thowe** [comment]
Nice.  Thank you for your answer and for working on this.
I hope to give it a try.

**Comment by japhb** [comment]
Good to see people making use of all that terminal code.  :-)
