### ISSUE TITLE
Weird, hard-to-release "dead keys" on Hungarian layout

### ISSUE THREAD

**Issue by 2colours** [japhb/Terminal-LineEditor#3]
Hello,

this time around, I'm illustrating the issue on Ubuntu 20.04 under WSL2, Windows 10. The results were pretty similar on a real Ubuntu 20.04 as well.

I need to press "alt gr" (the right alt, by other terminology) to access certain special characters; I noticed that when I fat-finger certain keys, the repl stops taking input. Eventually I found a few concrete keys and also keys to break out from this lock:

alt gr + d: this would be `Đ` normally. The sequence of dead keys alt gr + 3, alt gr + 2 gives an eventual `ć` character, or `ć^` when pressed the other way around (`^` is indeed the dead key symbol of alt gr + 3). A different way to break out: shift + ú gives an eventual `Ě`, or, alt gr + ú (normally `×`) gives an eventual `ė`.

alt gr + á: this would be `ß` normally. The same "escape sequences" worked, this time around with `Ç`, `Ú` and `×` respectively.

I don't know where these alternative characters even come from, and maybe there are others that I couldn't quickly find. For rationale: ß would be an easy misstype for $ on this layout, I think that's the most common source of problems. Anyway, if I start pressing keys at random, I can still bump into new problems and I don't know a way out for all of them.

Could you please look into what happens with the characters? I don't see anything similar in other terminal programs.

**Comment by japhb** [comment]
That's really odd -- I'll look into it.  Thanks for the report!

**Comment by japhb** [comment]
I set up *a* Hungarian layout on my (physically US) keyboard.  I can't recreate the exact behavior you're seeing, but I am finding some AltGr combinations that have to be pressed *twice* before they come through the byte stream, which is a bit odd.  I have a guess as to where that might be coming from, but it's a fairly weak guess.

Nevertheless, the first problem is that I can't recreate the actual behavior you're seeing, and this might be coming back to that point before about setting up *a* Hungarian layout.  My OS (Linux Mint, based on Ubuntu 20.04) offers me *20* different Hungarian layouts, and as far as I can tell, the one named just "Hungarian" isn't the same as the one you're using.  :frowning_face:  What's the exact name of your active layout?

**Comment by 2colours** [comment]
https://pasteboard.co/WyEan6VD3HjH.png

Well, this is the layout I'm using and I can confirm that the problem occurs for the same combinations on the bare metal usual Ubuntu 20.04 setup as well, with tiny differences.

**Comment by japhb** [comment]
(TL;DR: Haven't fixed the bug, but can now recreate and have narrowed the possible problems considerably.)

Thank you for the screenshot.  That led me to compare against `/usr/share/X11/xkb/symbols/hu` and I was able to match keyboard variants; I also did some research and found out that "pressed twice" is another way to get *just* the accent from a dead key (the apparent default being dead key + space).  So that was a red herring, and not a problem.

I went back to basics by testing the simplest version of my key parsing algorithm, the one in `Terminal::Print::RawInput`, using the `examples/raw-input.p6` program -- that seemed to work perfectly as the keymap and your description say that it *should*.  Going up a level in complexity, I then tried the `Terminal::Print::DecodedInput` algorithm, using `examples/decoded-input.p6`.  That worked perfectly as well, and ruled out that the fundamental "read bytes until able to decode as utf-8" algorithm was completely broken.

The version in `Terminal::LineEditor` is significantly more advanced, and uses `Terminal::ANSIParser` underneath to parse the binary ANSI/VT protocol that is overlaid on the raw input stream, allowing among other things direct querying of the VT emulator and parsing the results.  (Window resize without NativeCall or shelling out to `tput`!  Autodetection of truecolor support!  Unicorns and nyan cats!).  `Terminal::LineEditor` **doesn't** actually use `Terminal::Print`'s input libraries at all, but it uses a very similar method for assembling bytes off the wire, which is why I started with the easier codebase.

I pulled up a `raku` REPL with `Terminal::LineEditor` enabled, and tried the sequences you mentioned.  Sure enough, I could now recreate the problem -- somewhere in the pile of smarter, my parser also got dumber at the same time.  I now know roughly where to look.  More to come when I have more progress to report.

**Comment by japhb** [comment]
I've determined what is *wrong*, but not yet what to *do about it*.

Fundamentally this comes down to a conflict between behaviors defined for ANSI/VT processing (last standards update 1991) and UTF-8 encoding (first public mention 1993).  Essentially, the VT behavior is supposed to be byte-based, so that a C1 control code (in the range 0x80-0x9F) that affects the ANSI stream parser's state is handled immediately.  However, some UTF-8 continuation bytes (bytes 2 through 4) land in C1, so handling them immediately means breaking up the UTF-8 sequence, and it happens that Hungarian's very rich input keymap produces some graphemes that hit this.  This of course was no problem in the `Terminal::Print` modules because they made no attempt to follow the standard VT behavior.

One option is to add a UTF-8 compatibility mode in `Terminal::ANSIParser` that tries to do the right thing with partial UTF-8 sequences.  This is possible but notably error-prone, as evidenced by references I can find online that almost amount to pitched battles about "correct" recovery behavior when there are errors in the byte stream, not to mention a large number of security issues that have been found in such handling.  Significant effort went into getting this right in MoarVM (and thus Rakudo, for most users), so I'm not exactly keen on wading into that particular swamp if I don't have to.

Another option is to add a "disable C1" mode in `Terminal::ANSIParser`, to avoid the conflict in byte interpretation entirely at the expense of not handling mixed C0 and C1 control streams.  This might not actually be a problem in real usage; it wasn't until later DEC VT models that C1 codes were even supported in the first place, so lots of code is written using only the C0 control codes and the 2-septet equivalents for the C1 codes.  It rankles a bit that the parser with that option set would ignore C1 codes even when they are *not* following a UTF-8 initial byte, but there's something to be said for simplicity of behavior (after all, parsing an ANSI VT byte stream is already a bit of a mess).

A related option (and the one I'm currently leaning towards) is to semantically generalize the option -- let the code calling `make-ansi-parser()` state how it wants C1 codes to be handled, but *for now* only support always-ignore and always-respond modes -- and make always-ignore the default, since it probably makes the most sense for current callers that expect UTF-8 to Just Work.  Programmers working on their own VT emulator or screen/tmux-equivalent still have the option of getting the classical/standards-compliant behavior, and it may be possible to support more "clever" modes later.

**Comment by japhb** [comment]
There is another option: Make the parser resilient to being asked to parse numbers that won't fit into a byte.

If you want UTF-8 decoding to take precedence over ANSI/VT processing, then you simply do the UTF-8 decoding *first* and the resilient parser would know that if there's still a C1 byte in the stream then it's a "real" C1, because there won't be continuation bytes in the stream anymore.  Because this would be handling previously invalid inputs without changing other existing behavior, giving it some useful compatibility properties, I'm going to investigate this one first and see if it can be made to work without painful changes to the parser.

If you wanted ANSI/VT C1 parsing to take precedence over UTF-8 decoding, then you could still do the UTF-8 decoding of the *output* of the ANSI parser (as `Terminal::LineEditor` has done up until now).  This is probably not useful for anything trying to DWIM for today's expectations, but provides an option for those who want to exactly replicate standardized terminal behavior.

Once `Terminal::ANSIParser` is resilient to large input values, then I can release it and make a `Terminal::LineEditor` that relies on the new behavior and moves the UTF-8 decoding to the front of the parsing chain.

**Comment by japhb** [comment]
New versions of `Terminal::ANSIParser` and `Terminal::LineEditor` released.  This bug appears fixed to be as of `Terminal::LineEditor` `0.0.12` (which automatically requires the correct matching `Terminal::ANSIParser` release).

Feel free to reopen if it *doesn't* work for you after upgrading `Terminal::LineEditor` (it works for me given all the cases you described).  Thanks again for the report!
